import {authOptions} from '../pages/api/auth/[...nextauth]'

import './globals.css'
import SessionProvider from '../components/SessionProvider'
import { getServerSession } from 'next-auth'
import SignIn from '@/pages/auth/signin'
import ClientProvider from '@/components/ClientProvider'

export const metadata = {
  title: 'Instagram',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session} >
        
          { session ? 
          <SignIn providers={''} />
          :
            
          <div>
            <ClientProvider />
            {children}
          </div>}
        
        </SessionProvider>
      </body>
    </html>
  )
}
